//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistRepos.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class canceladas
    {
        [Display(Name = "Reposicion")]
        public int idReposicion { get; set; }
        [Display(Name = "Solicitante")]
        public string idSolicitante { get; set; }
        [Display(Name = "Creacion")]
        public Nullable<System.DateTime> horaCreacion { get; set; }
        [Display(Name = "Cancelación")]
        public Nullable<System.DateTime> horaCancelacion { get; set; }
        [Display(Name = "Herramienta")]
        public Nullable<int> idHerramienta { get; set; }
        [Display(Name = "Puesto")]
        public Nullable<int> idPuesto { get; set; }
    }
}
