//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistRepos.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class estados
    {
        public estados()
        {
            this.reposiciones = new HashSet<reposiciones>();
        }
    
        public int idEstado { get; set; }
        [Display(Name = "Estado")]
        public string estado { get; set; }
    
        public virtual ICollection<reposiciones> reposiciones { get; set; }
    }
}
