//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistRepos.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class localidades
    {
        public localidades()
        {
            this.usuarios = new HashSet<usuarios>();
        }
    
        public int idLocalidad { get; set; }
        [Display(Name = "Localidad")]
        public string localidad { get; set; }
        public Nullable<int> idProvincia { get; set; }
    
        public virtual ICollection<usuarios> usuarios { get; set; }
        public virtual provincias provincias { get; set; }
    }
}
