//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistRepos.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class pisos
    {
        public pisos()
        {
            this.puestos = new HashSet<puestos>();
        }
    
        public int idPiso { get; set; }
        public Nullable<int> idSucursal { get; set; }
        [Display(Name = "Piso")]
        public Nullable<int> piso { get; set; }
    
        public virtual ICollection<puestos> puestos { get; set; }
        public virtual sucursales sucursales { get; set; }
    }
}
