//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistRepos.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class provincias
    {
        public provincias()
        {
            this.localidades = new HashSet<localidades>();
        }
    
        public int idProvincia { get; set; }
        [Display(Name = "Provincia")]
        public string provincia { get; set; }
    
        public virtual ICollection<localidades> localidades { get; set; }
    }
}
