//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistRepos.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class roles
    {
        public roles()
        {
            this.usuarios = new HashSet<usuarios>();
        }
    
        public string idRol { get; set; }
        [Display(Name = "Función")]
        public string rol { get; set; }
    
        public virtual ICollection<usuarios> usuarios { get; set; }
    }
}
